// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2HLI14ADswr2awCObbJB6BAW7ifdXcME',
    appId: '1:1094974185634:web:709192ac12a4573f6c77fb',
    messagingSenderId: '1094974185634',
    projectId: 'chat-df228',
    authDomain: 'chat-df228.firebaseapp.com',
    storageBucket: 'chat-df228.appspot.com',
    measurementId: 'G-JQGFEWW1SN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCenDkjI2YeHZd0FYGIIRmerpIMBMSG2eo',
    appId: '1:1094974185634:android:53f65df12816f53b6c77fb',
    messagingSenderId: '1094974185634',
    projectId: 'chat-df228',
    storageBucket: 'chat-df228.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEEPqcymoy8xolliFHRT1QNKz7kSLXGu0',
    appId: '1:1094974185634:ios:618baf6b37a768566c77fb',
    messagingSenderId: '1094974185634',
    projectId: 'chat-df228',
    storageBucket: 'chat-df228.appspot.com',
    iosBundleId: 'com.example.chatmessengerapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEEPqcymoy8xolliFHRT1QNKz7kSLXGu0',
    appId: '1:1094974185634:ios:3133fa79f3a8b1bb6c77fb',
    messagingSenderId: '1094974185634',
    projectId: 'chat-df228',
    storageBucket: 'chat-df228.appspot.com',
    iosBundleId: 'com.example.chatmessengerapp.RunnerTests',
  );
}
